// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

public interface ChunkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChunkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * MD5 of the file content
   * </pre>
   *
   * <code>bytes fileHash = 1;</code>
   */
  com.google.protobuf.ByteString getFileHash();

  /**
   * <code>uint32 chunkIndex = 2;</code>
   */
  int getChunkIndex();
}
