// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

/**
 * <pre>
 * Parties:
 *   Node -&gt; Node
 * Description:
 *   Download the specified chunk.
 * Response status:
 *   - SUCCESS if you have the chunk
 *   - MESSAGE_ERROR if the filehash is not 16 bytes long or the index is less than zero
 *   - UNABLE_TO_COMPLETE if you do not have the chunk
 *   - PROCESSING_ERROR in all other cases
 * </pre>
 *
 * Protobuf type {@code ChunkRequest}
 */
public  final class ChunkRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChunkRequest)
    ChunkRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChunkRequest.newBuilder() to construct.
  private ChunkRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChunkRequest() {
    fileHash_ = com.google.protobuf.ByteString.EMPTY;
    chunkIndex_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChunkRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            fileHash_ = input.readBytes();
            break;
          }
          case 16: {

            chunkIndex_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.java.entities.Torr.internal_static_ChunkRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.java.entities.Torr.internal_static_ChunkRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.java.entities.ChunkRequest.class, main.java.entities.ChunkRequest.Builder.class);
  }

  public static final int FILEHASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString fileHash_;
  /**
   * <pre>
   * MD5 of the file content
   * </pre>
   *
   * <code>bytes fileHash = 1;</code>
   */
  public com.google.protobuf.ByteString getFileHash() {
    return fileHash_;
  }

  public static final int CHUNKINDEX_FIELD_NUMBER = 2;
  private int chunkIndex_;
  /**
   * <code>uint32 chunkIndex = 2;</code>
   */
  public int getChunkIndex() {
    return chunkIndex_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!fileHash_.isEmpty()) {
      output.writeBytes(1, fileHash_);
    }
    if (chunkIndex_ != 0) {
      output.writeUInt32(2, chunkIndex_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!fileHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, fileHash_);
    }
    if (chunkIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, chunkIndex_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof main.java.entities.ChunkRequest)) {
      return super.equals(obj);
    }
    main.java.entities.ChunkRequest other = (main.java.entities.ChunkRequest) obj;

    boolean result = true;
    result = result && getFileHash()
        .equals(other.getFileHash());
    result = result && (getChunkIndex()
        == other.getChunkIndex());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILEHASH_FIELD_NUMBER;
    hash = (53 * hash) + getFileHash().hashCode();
    hash = (37 * hash) + CHUNKINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getChunkIndex();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static main.java.entities.ChunkRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.entities.ChunkRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.entities.ChunkRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.entities.ChunkRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.entities.ChunkRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.entities.ChunkRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.entities.ChunkRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.java.entities.ChunkRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.java.entities.ChunkRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static main.java.entities.ChunkRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.java.entities.ChunkRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.java.entities.ChunkRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.java.entities.ChunkRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Parties:
   *   Node -&gt; Node
   * Description:
   *   Download the specified chunk.
   * Response status:
   *   - SUCCESS if you have the chunk
   *   - MESSAGE_ERROR if the filehash is not 16 bytes long or the index is less than zero
   *   - UNABLE_TO_COMPLETE if you do not have the chunk
   *   - PROCESSING_ERROR in all other cases
   * </pre>
   *
   * Protobuf type {@code ChunkRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChunkRequest)
      main.java.entities.ChunkRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.java.entities.Torr.internal_static_ChunkRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.java.entities.Torr.internal_static_ChunkRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.java.entities.ChunkRequest.class, main.java.entities.ChunkRequest.Builder.class);
    }

    // Construct using main.java.entities.ChunkRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      fileHash_ = com.google.protobuf.ByteString.EMPTY;

      chunkIndex_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.java.entities.Torr.internal_static_ChunkRequest_descriptor;
    }

    public main.java.entities.ChunkRequest getDefaultInstanceForType() {
      return main.java.entities.ChunkRequest.getDefaultInstance();
    }

    public main.java.entities.ChunkRequest build() {
      main.java.entities.ChunkRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public main.java.entities.ChunkRequest buildPartial() {
      main.java.entities.ChunkRequest result = new main.java.entities.ChunkRequest(this);
      result.fileHash_ = fileHash_;
      result.chunkIndex_ = chunkIndex_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.java.entities.ChunkRequest) {
        return mergeFrom((main.java.entities.ChunkRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.java.entities.ChunkRequest other) {
      if (other == main.java.entities.ChunkRequest.getDefaultInstance()) return this;
      if (other.getFileHash() != com.google.protobuf.ByteString.EMPTY) {
        setFileHash(other.getFileHash());
      }
      if (other.getChunkIndex() != 0) {
        setChunkIndex(other.getChunkIndex());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.java.entities.ChunkRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.java.entities.ChunkRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString fileHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * MD5 of the file content
     * </pre>
     *
     * <code>bytes fileHash = 1;</code>
     */
    public com.google.protobuf.ByteString getFileHash() {
      return fileHash_;
    }
    /**
     * <pre>
     * MD5 of the file content
     * </pre>
     *
     * <code>bytes fileHash = 1;</code>
     */
    public Builder setFileHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fileHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * MD5 of the file content
     * </pre>
     *
     * <code>bytes fileHash = 1;</code>
     */
    public Builder clearFileHash() {
      
      fileHash_ = getDefaultInstance().getFileHash();
      onChanged();
      return this;
    }

    private int chunkIndex_ ;
    /**
     * <code>uint32 chunkIndex = 2;</code>
     */
    public int getChunkIndex() {
      return chunkIndex_;
    }
    /**
     * <code>uint32 chunkIndex = 2;</code>
     */
    public Builder setChunkIndex(int value) {
      
      chunkIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 chunkIndex = 2;</code>
     */
    public Builder clearChunkIndex() {
      
      chunkIndex_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChunkRequest)
  }

  // @@protoc_insertion_point(class_scope:ChunkRequest)
  private static final main.java.entities.ChunkRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.java.entities.ChunkRequest();
  }

  public static main.java.entities.ChunkRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChunkRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChunkRequest>() {
    public ChunkRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChunkRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChunkRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChunkRequest> getParserForType() {
    return PARSER;
  }

  public main.java.entities.ChunkRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

