// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

public interface FileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * MD5 of the file content
   * </pre>
   *
   * <code>bytes hash = 1;</code>
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>uint32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>string filename = 3;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 3;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>repeated .ChunkInfo chunks = 4;</code>
   */
  java.util.List<main.java.entities.ChunkInfo> 
      getChunksList();
  /**
   * <code>repeated .ChunkInfo chunks = 4;</code>
   */
  main.java.entities.ChunkInfo getChunks(int index);
  /**
   * <code>repeated .ChunkInfo chunks = 4;</code>
   */
  int getChunksCount();
  /**
   * <code>repeated .ChunkInfo chunks = 4;</code>
   */
  java.util.List<? extends main.java.entities.ChunkInfoOrBuilder> 
      getChunksOrBuilderList();
  /**
   * <code>repeated .ChunkInfo chunks = 4;</code>
   */
  main.java.entities.ChunkInfoOrBuilder getChunksOrBuilder(
      int index);
}
