// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Message.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.Message.Type type = 1;</code>
   */
  main.java.entities.Message.Type getType();

  /**
   * <code>.LocalSearchRequest localSearchRequest = 2;</code>
   */
  boolean hasLocalSearchRequest();
  /**
   * <code>.LocalSearchRequest localSearchRequest = 2;</code>
   */
  main.java.entities.LocalSearchRequest getLocalSearchRequest();
  /**
   * <code>.LocalSearchRequest localSearchRequest = 2;</code>
   */
  main.java.entities.LocalSearchRequestOrBuilder getLocalSearchRequestOrBuilder();

  /**
   * <code>.LocalSearchResponse localSearchResponse = 3;</code>
   */
  boolean hasLocalSearchResponse();
  /**
   * <code>.LocalSearchResponse localSearchResponse = 3;</code>
   */
  main.java.entities.LocalSearchResponse getLocalSearchResponse();
  /**
   * <code>.LocalSearchResponse localSearchResponse = 3;</code>
   */
  main.java.entities.LocalSearchResponseOrBuilder getLocalSearchResponseOrBuilder();

  /**
   * <code>.SearchRequest searchRequest = 4;</code>
   */
  boolean hasSearchRequest();
  /**
   * <code>.SearchRequest searchRequest = 4;</code>
   */
  main.java.entities.SearchRequest getSearchRequest();
  /**
   * <code>.SearchRequest searchRequest = 4;</code>
   */
  main.java.entities.SearchRequestOrBuilder getSearchRequestOrBuilder();

  /**
   * <code>.SearchResponse searchResponse = 5;</code>
   */
  boolean hasSearchResponse();
  /**
   * <code>.SearchResponse searchResponse = 5;</code>
   */
  main.java.entities.SearchResponse getSearchResponse();
  /**
   * <code>.SearchResponse searchResponse = 5;</code>
   */
  main.java.entities.SearchResponseOrBuilder getSearchResponseOrBuilder();

  /**
   * <code>.UploadRequest uploadRequest = 6;</code>
   */
  boolean hasUploadRequest();
  /**
   * <code>.UploadRequest uploadRequest = 6;</code>
   */
  main.java.entities.UploadRequest getUploadRequest();
  /**
   * <code>.UploadRequest uploadRequest = 6;</code>
   */
  main.java.entities.UploadRequestOrBuilder getUploadRequestOrBuilder();

  /**
   * <code>.UploadResponse uploadResponse = 7;</code>
   */
  boolean hasUploadResponse();
  /**
   * <code>.UploadResponse uploadResponse = 7;</code>
   */
  main.java.entities.UploadResponse getUploadResponse();
  /**
   * <code>.UploadResponse uploadResponse = 7;</code>
   */
  main.java.entities.UploadResponseOrBuilder getUploadResponseOrBuilder();

  /**
   * <code>.ReplicateRequest replicateRequest = 8;</code>
   */
  boolean hasReplicateRequest();
  /**
   * <code>.ReplicateRequest replicateRequest = 8;</code>
   */
  main.java.entities.ReplicateRequest getReplicateRequest();
  /**
   * <code>.ReplicateRequest replicateRequest = 8;</code>
   */
  main.java.entities.ReplicateRequestOrBuilder getReplicateRequestOrBuilder();

  /**
   * <code>.ReplicateResponse replicateResponse = 9;</code>
   */
  boolean hasReplicateResponse();
  /**
   * <code>.ReplicateResponse replicateResponse = 9;</code>
   */
  main.java.entities.ReplicateResponse getReplicateResponse();
  /**
   * <code>.ReplicateResponse replicateResponse = 9;</code>
   */
  main.java.entities.ReplicateResponseOrBuilder getReplicateResponseOrBuilder();

  /**
   * <code>.ChunkRequest chunkRequest = 10;</code>
   */
  boolean hasChunkRequest();
  /**
   * <code>.ChunkRequest chunkRequest = 10;</code>
   */
  main.java.entities.ChunkRequest getChunkRequest();
  /**
   * <code>.ChunkRequest chunkRequest = 10;</code>
   */
  main.java.entities.ChunkRequestOrBuilder getChunkRequestOrBuilder();

  /**
   * <code>.ChunkResponse chunkResponse = 11;</code>
   */
  boolean hasChunkResponse();
  /**
   * <code>.ChunkResponse chunkResponse = 11;</code>
   */
  main.java.entities.ChunkResponse getChunkResponse();
  /**
   * <code>.ChunkResponse chunkResponse = 11;</code>
   */
  main.java.entities.ChunkResponseOrBuilder getChunkResponseOrBuilder();

  /**
   * <code>.DownloadRequest downloadRequest = 12;</code>
   */
  boolean hasDownloadRequest();
  /**
   * <code>.DownloadRequest downloadRequest = 12;</code>
   */
  main.java.entities.DownloadRequest getDownloadRequest();
  /**
   * <code>.DownloadRequest downloadRequest = 12;</code>
   */
  main.java.entities.DownloadRequestOrBuilder getDownloadRequestOrBuilder();

  /**
   * <code>.DownloadResponse downloadResponse = 13;</code>
   */
  boolean hasDownloadResponse();
  /**
   * <code>.DownloadResponse downloadResponse = 13;</code>
   */
  main.java.entities.DownloadResponse getDownloadResponse();
  /**
   * <code>.DownloadResponse downloadResponse = 13;</code>
   */
  main.java.entities.DownloadResponseOrBuilder getDownloadResponseOrBuilder();
}
