// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

public interface NodeReplicationStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeReplicationStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   */
  main.java.entities.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  main.java.entities.NodeOrBuilder getNodeOrBuilder();

  /**
   * <code>uint32 chunkIndex = 2;</code>
   */
  int getChunkIndex();

  /**
   * <code>.Status status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 3;</code>
   */
  main.java.entities.Status getStatus();

  /**
   * <code>string errorMessage = 4;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 4;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
