// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

public interface NodeSearchResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeSearchResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   */
  main.java.entities.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  main.java.entities.NodeOrBuilder getNodeOrBuilder();

  /**
   * <code>.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 2;</code>
   */
  main.java.entities.Status getStatus();

  /**
   * <code>string errorMessage = 3;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>repeated .FileInfo files = 4;</code>
   */
  java.util.List<main.java.entities.FileInfo> 
      getFilesList();
  /**
   * <code>repeated .FileInfo files = 4;</code>
   */
  main.java.entities.FileInfo getFiles(int index);
  /**
   * <code>repeated .FileInfo files = 4;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .FileInfo files = 4;</code>
   */
  java.util.List<? extends main.java.entities.FileInfoOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .FileInfo files = 4;</code>
   */
  main.java.entities.FileInfoOrBuilder getFilesOrBuilder(
      int index);
}
