// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

/**
 * <pre>
 * Parties:
 *   Client -&gt; Node
 * Description:
 *   Replicate this file locally, if not present already. Ask for chunks from the other nodes using ChunkRequest.
 *   If a ChunkRequest fails, send it to another node until you tried al nodes. If none of the nodes gives you that
 *   chunk's data,
 * Response status:
 *   - SUCCESS if all went well, even if you have the file already
 *   - MESSAGE_ERROR if the filename in the FileInfo is empty
 *   - UNABLE_TO_COMPLETE if you cannot receive all the chunks from the other nodes
 *   - PROCESSING_ERROR in all other cases
 * NodeReplication status:
 *   - NETWORK_ERROR if you cannot connect to the node
 *   - MESSAGE_ERROR if the response is not parsable or has the wrong type
 *   - Otherwise, use ChunkResponse.status
 * </pre>
 *
 * Protobuf type {@code ReplicateRequest}
 */
public  final class ReplicateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReplicateRequest)
    ReplicateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReplicateRequest.newBuilder() to construct.
  private ReplicateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplicateRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReplicateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            main.java.entities.FileInfo.Builder subBuilder = null;
            if (fileInfo_ != null) {
              subBuilder = fileInfo_.toBuilder();
            }
            fileInfo_ = input.readMessage(main.java.entities.FileInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fileInfo_);
              fileInfo_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.java.entities.Torr.internal_static_ReplicateRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.java.entities.Torr.internal_static_ReplicateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.java.entities.ReplicateRequest.class, main.java.entities.ReplicateRequest.Builder.class);
  }

  public static final int FILEINFO_FIELD_NUMBER = 1;
  private main.java.entities.FileInfo fileInfo_;
  /**
   * <code>.FileInfo fileInfo = 1;</code>
   */
  public boolean hasFileInfo() {
    return fileInfo_ != null;
  }
  /**
   * <code>.FileInfo fileInfo = 1;</code>
   */
  public main.java.entities.FileInfo getFileInfo() {
    return fileInfo_ == null ? main.java.entities.FileInfo.getDefaultInstance() : fileInfo_;
  }
  /**
   * <code>.FileInfo fileInfo = 1;</code>
   */
  public main.java.entities.FileInfoOrBuilder getFileInfoOrBuilder() {
    return getFileInfo();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fileInfo_ != null) {
      output.writeMessage(1, getFileInfo());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fileInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFileInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof main.java.entities.ReplicateRequest)) {
      return super.equals(obj);
    }
    main.java.entities.ReplicateRequest other = (main.java.entities.ReplicateRequest) obj;

    boolean result = true;
    result = result && (hasFileInfo() == other.hasFileInfo());
    if (hasFileInfo()) {
      result = result && getFileInfo()
          .equals(other.getFileInfo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFileInfo()) {
      hash = (37 * hash) + FILEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getFileInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static main.java.entities.ReplicateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.entities.ReplicateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.entities.ReplicateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.entities.ReplicateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.entities.ReplicateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.entities.ReplicateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.entities.ReplicateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.java.entities.ReplicateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.java.entities.ReplicateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static main.java.entities.ReplicateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static main.java.entities.ReplicateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static main.java.entities.ReplicateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.java.entities.ReplicateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Parties:
   *   Client -&gt; Node
   * Description:
   *   Replicate this file locally, if not present already. Ask for chunks from the other nodes using ChunkRequest.
   *   If a ChunkRequest fails, send it to another node until you tried al nodes. If none of the nodes gives you that
   *   chunk's data,
   * Response status:
   *   - SUCCESS if all went well, even if you have the file already
   *   - MESSAGE_ERROR if the filename in the FileInfo is empty
   *   - UNABLE_TO_COMPLETE if you cannot receive all the chunks from the other nodes
   *   - PROCESSING_ERROR in all other cases
   * NodeReplication status:
   *   - NETWORK_ERROR if you cannot connect to the node
   *   - MESSAGE_ERROR if the response is not parsable or has the wrong type
   *   - Otherwise, use ChunkResponse.status
   * </pre>
   *
   * Protobuf type {@code ReplicateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReplicateRequest)
      main.java.entities.ReplicateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.java.entities.Torr.internal_static_ReplicateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.java.entities.Torr.internal_static_ReplicateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.java.entities.ReplicateRequest.class, main.java.entities.ReplicateRequest.Builder.class);
    }

    // Construct using main.java.entities.ReplicateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (fileInfoBuilder_ == null) {
        fileInfo_ = null;
      } else {
        fileInfo_ = null;
        fileInfoBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.java.entities.Torr.internal_static_ReplicateRequest_descriptor;
    }

    public main.java.entities.ReplicateRequest getDefaultInstanceForType() {
      return main.java.entities.ReplicateRequest.getDefaultInstance();
    }

    public main.java.entities.ReplicateRequest build() {
      main.java.entities.ReplicateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public main.java.entities.ReplicateRequest buildPartial() {
      main.java.entities.ReplicateRequest result = new main.java.entities.ReplicateRequest(this);
      if (fileInfoBuilder_ == null) {
        result.fileInfo_ = fileInfo_;
      } else {
        result.fileInfo_ = fileInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.java.entities.ReplicateRequest) {
        return mergeFrom((main.java.entities.ReplicateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.java.entities.ReplicateRequest other) {
      if (other == main.java.entities.ReplicateRequest.getDefaultInstance()) return this;
      if (other.hasFileInfo()) {
        mergeFileInfo(other.getFileInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.java.entities.ReplicateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.java.entities.ReplicateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private main.java.entities.FileInfo fileInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        main.java.entities.FileInfo, main.java.entities.FileInfo.Builder, main.java.entities.FileInfoOrBuilder> fileInfoBuilder_;
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public boolean hasFileInfo() {
      return fileInfoBuilder_ != null || fileInfo_ != null;
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public main.java.entities.FileInfo getFileInfo() {
      if (fileInfoBuilder_ == null) {
        return fileInfo_ == null ? main.java.entities.FileInfo.getDefaultInstance() : fileInfo_;
      } else {
        return fileInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public Builder setFileInfo(main.java.entities.FileInfo value) {
      if (fileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fileInfo_ = value;
        onChanged();
      } else {
        fileInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public Builder setFileInfo(
        main.java.entities.FileInfo.Builder builderForValue) {
      if (fileInfoBuilder_ == null) {
        fileInfo_ = builderForValue.build();
        onChanged();
      } else {
        fileInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public Builder mergeFileInfo(main.java.entities.FileInfo value) {
      if (fileInfoBuilder_ == null) {
        if (fileInfo_ != null) {
          fileInfo_ =
            main.java.entities.FileInfo.newBuilder(fileInfo_).mergeFrom(value).buildPartial();
        } else {
          fileInfo_ = value;
        }
        onChanged();
      } else {
        fileInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public Builder clearFileInfo() {
      if (fileInfoBuilder_ == null) {
        fileInfo_ = null;
        onChanged();
      } else {
        fileInfo_ = null;
        fileInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public main.java.entities.FileInfo.Builder getFileInfoBuilder() {
      
      onChanged();
      return getFileInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    public main.java.entities.FileInfoOrBuilder getFileInfoOrBuilder() {
      if (fileInfoBuilder_ != null) {
        return fileInfoBuilder_.getMessageOrBuilder();
      } else {
        return fileInfo_ == null ?
            main.java.entities.FileInfo.getDefaultInstance() : fileInfo_;
      }
    }
    /**
     * <code>.FileInfo fileInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        main.java.entities.FileInfo, main.java.entities.FileInfo.Builder, main.java.entities.FileInfoOrBuilder> 
        getFileInfoFieldBuilder() {
      if (fileInfoBuilder_ == null) {
        fileInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            main.java.entities.FileInfo, main.java.entities.FileInfo.Builder, main.java.entities.FileInfoOrBuilder>(
                getFileInfo(),
                getParentForChildren(),
                isClean());
        fileInfo_ = null;
      }
      return fileInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReplicateRequest)
  }

  // @@protoc_insertion_point(class_scope:ReplicateRequest)
  private static final main.java.entities.ReplicateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.java.entities.ReplicateRequest();
  }

  public static main.java.entities.ReplicateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplicateRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReplicateRequest>() {
    public ReplicateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReplicateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplicateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplicateRequest> getParserForType() {
    return PARSER;
  }

  public main.java.entities.ReplicateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

