// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package main.java.entities;

public interface UploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 1;</code>
   */
  main.java.entities.Status getStatus();

  /**
   * <code>string errorMessage = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * The FileInfo you stored or had already
   * </pre>
   *
   * <code>.FileInfo fileInfo = 3;</code>
   */
  boolean hasFileInfo();
  /**
   * <pre>
   * The FileInfo you stored or had already
   * </pre>
   *
   * <code>.FileInfo fileInfo = 3;</code>
   */
  main.java.entities.FileInfo getFileInfo();
  /**
   * <pre>
   * The FileInfo you stored or had already
   * </pre>
   *
   * <code>.FileInfo fileInfo = 3;</code>
   */
  main.java.entities.FileInfoOrBuilder getFileInfoOrBuilder();
}
