// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface ChunkInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChunkInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Chunk order number starting from 0
   * </pre>
   *
   * <code>uint32 index = 1;</code>
   */
  int getIndex();

  /**
   * <pre>
   * The standard chunk size is 1024. Last chunks will be smaller.
   * </pre>
   *
   * <code>uint32 size = 2;</code>
   */
  int getSize();

  /**
   * <pre>
   * MD5 of the chunk content (1024 bytes or less)
   * </pre>
   *
   * <code>bytes hash = 3;</code>
   */
  com.google.protobuf.ByteString getHash();
}
