// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface DownloadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DownloadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * MD5 of the file content
   * </pre>
   *
   * <code>bytes fileHash = 1;</code>
   */
  com.google.protobuf.ByteString getFileHash();
}
