// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface LocalSearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocalSearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 1;</code>
   */
  entities.Status getStatus();

  /**
   * <code>string errorMessage = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>repeated .FileInfo fileInfo = 3;</code>
   */
  java.util.List<entities.FileInfo> 
      getFileInfoList();
  /**
   * <code>repeated .FileInfo fileInfo = 3;</code>
   */
  entities.FileInfo getFileInfo(int index);
  /**
   * <code>repeated .FileInfo fileInfo = 3;</code>
   */
  int getFileInfoCount();
  /**
   * <code>repeated .FileInfo fileInfo = 3;</code>
   */
  java.util.List<? extends entities.FileInfoOrBuilder> 
      getFileInfoOrBuilderList();
  /**
   * <code>repeated .FileInfo fileInfo = 3;</code>
   */
  entities.FileInfoOrBuilder getFileInfoOrBuilder(
      int index);
}
