// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface ReplicateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReplicateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 1;</code>
   */
  entities.Status getStatus();

  /**
   * <code>string errorMessage = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * The status of all the requests to other nodes
   * </pre>
   *
   * <code>repeated .NodeReplicationStatus nodeStatusList = 3;</code>
   */
  java.util.List<entities.NodeReplicationStatus> 
      getNodeStatusListList();
  /**
   * <pre>
   * The status of all the requests to other nodes
   * </pre>
   *
   * <code>repeated .NodeReplicationStatus nodeStatusList = 3;</code>
   */
  entities.NodeReplicationStatus getNodeStatusList(int index);
  /**
   * <pre>
   * The status of all the requests to other nodes
   * </pre>
   *
   * <code>repeated .NodeReplicationStatus nodeStatusList = 3;</code>
   */
  int getNodeStatusListCount();
  /**
   * <pre>
   * The status of all the requests to other nodes
   * </pre>
   *
   * <code>repeated .NodeReplicationStatus nodeStatusList = 3;</code>
   */
  java.util.List<? extends entities.NodeReplicationStatusOrBuilder> 
      getNodeStatusListOrBuilderList();
  /**
   * <pre>
   * The status of all the requests to other nodes
   * </pre>
   *
   * <code>repeated .NodeReplicationStatus nodeStatusList = 3;</code>
   */
  entities.NodeReplicationStatusOrBuilder getNodeStatusListOrBuilder(
      int index);
}
