// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

/**
 * Protobuf enum {@code Status}
 */
public enum Status
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <pre>
   * there are no errors, but the requested operation cannot be completed
   * </pre>
   *
   * <code>UNABLE_TO_COMPLETE = 1;</code>
   */
  UNABLE_TO_COMPLETE(1),
  /**
   * <pre>
   * the incoming request or response is invalid in some way
   * </pre>
   *
   * <code>MESSAGE_ERROR = 2;</code>
   */
  MESSAGE_ERROR(2),
  /**
   * <pre>
   * any network communication problem
   * </pre>
   *
   * <code>NETWORK_ERROR = 3;</code>
   */
  NETWORK_ERROR(3),
  /**
   * <pre>
   * any other error
   * </pre>
   *
   * <code>PROCESSING_ERROR = 4;</code>
   */
  PROCESSING_ERROR(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <pre>
   * there are no errors, but the requested operation cannot be completed
   * </pre>
   *
   * <code>UNABLE_TO_COMPLETE = 1;</code>
   */
  public static final int UNABLE_TO_COMPLETE_VALUE = 1;
  /**
   * <pre>
   * the incoming request or response is invalid in some way
   * </pre>
   *
   * <code>MESSAGE_ERROR = 2;</code>
   */
  public static final int MESSAGE_ERROR_VALUE = 2;
  /**
   * <pre>
   * any network communication problem
   * </pre>
   *
   * <code>NETWORK_ERROR = 3;</code>
   */
  public static final int NETWORK_ERROR_VALUE = 3;
  /**
   * <pre>
   * any other error
   * </pre>
   *
   * <code>PROCESSING_ERROR = 4;</code>
   */
  public static final int PROCESSING_ERROR_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Status valueOf(int value) {
    return forNumber(value);
  }

  public static Status forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return UNABLE_TO_COMPLETE;
      case 2: return MESSAGE_ERROR;
      case 3: return NETWORK_ERROR;
      case 4: return PROCESSING_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Status>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Status> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Status>() {
          public Status findValueByNumber(int number) {
            return Status.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return entities.Torr.getDescriptor().getEnumTypes().get(0);
  }

  private static final Status[] VALUES = values();

  public static Status valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Status)
}

