// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

/**
 * <pre>
 * Wrapper message
 * </pre>
 *
 * Protobuf type {@code Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    type_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            entities.LocalSearchRequest.Builder subBuilder = null;
            if (localSearchRequest_ != null) {
              subBuilder = localSearchRequest_.toBuilder();
            }
            localSearchRequest_ = input.readMessage(entities.LocalSearchRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(localSearchRequest_);
              localSearchRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            entities.LocalSearchResponse.Builder subBuilder = null;
            if (localSearchResponse_ != null) {
              subBuilder = localSearchResponse_.toBuilder();
            }
            localSearchResponse_ = input.readMessage(entities.LocalSearchResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(localSearchResponse_);
              localSearchResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            entities.SearchRequest.Builder subBuilder = null;
            if (searchRequest_ != null) {
              subBuilder = searchRequest_.toBuilder();
            }
            searchRequest_ = input.readMessage(entities.SearchRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(searchRequest_);
              searchRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            entities.SearchResponse.Builder subBuilder = null;
            if (searchResponse_ != null) {
              subBuilder = searchResponse_.toBuilder();
            }
            searchResponse_ = input.readMessage(entities.SearchResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(searchResponse_);
              searchResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            entities.UploadRequest.Builder subBuilder = null;
            if (uploadRequest_ != null) {
              subBuilder = uploadRequest_.toBuilder();
            }
            uploadRequest_ = input.readMessage(entities.UploadRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(uploadRequest_);
              uploadRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            entities.UploadResponse.Builder subBuilder = null;
            if (uploadResponse_ != null) {
              subBuilder = uploadResponse_.toBuilder();
            }
            uploadResponse_ = input.readMessage(entities.UploadResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(uploadResponse_);
              uploadResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            entities.ReplicateRequest.Builder subBuilder = null;
            if (replicateRequest_ != null) {
              subBuilder = replicateRequest_.toBuilder();
            }
            replicateRequest_ = input.readMessage(entities.ReplicateRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(replicateRequest_);
              replicateRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            entities.ReplicateResponse.Builder subBuilder = null;
            if (replicateResponse_ != null) {
              subBuilder = replicateResponse_.toBuilder();
            }
            replicateResponse_ = input.readMessage(entities.ReplicateResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(replicateResponse_);
              replicateResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            entities.ChunkRequest.Builder subBuilder = null;
            if (chunkRequest_ != null) {
              subBuilder = chunkRequest_.toBuilder();
            }
            chunkRequest_ = input.readMessage(entities.ChunkRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chunkRequest_);
              chunkRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            entities.ChunkResponse.Builder subBuilder = null;
            if (chunkResponse_ != null) {
              subBuilder = chunkResponse_.toBuilder();
            }
            chunkResponse_ = input.readMessage(entities.ChunkResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chunkResponse_);
              chunkResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 98: {
            entities.DownloadRequest.Builder subBuilder = null;
            if (downloadRequest_ != null) {
              subBuilder = downloadRequest_.toBuilder();
            }
            downloadRequest_ = input.readMessage(entities.DownloadRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(downloadRequest_);
              downloadRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            entities.DownloadResponse.Builder subBuilder = null;
            if (downloadResponse_ != null) {
              subBuilder = downloadResponse_.toBuilder();
            }
            downloadResponse_ = input.readMessage(entities.DownloadResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(downloadResponse_);
              downloadResponse_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return entities.Torr.internal_static_Message_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return entities.Torr.internal_static_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            entities.Message.class, entities.Message.Builder.class);
  }

  /**
   * Protobuf enum {@code Message.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOCAL_SEARCH_REQUEST = 0;</code>
     */
    LOCAL_SEARCH_REQUEST(0),
    /**
     * <code>LOCAL_SEARCH_RESPONSE = 1;</code>
     */
    LOCAL_SEARCH_RESPONSE(1),
    /**
     * <code>SEARCH_REQUEST = 2;</code>
     */
    SEARCH_REQUEST(2),
    /**
     * <code>SEARCH_RESPONSE = 3;</code>
     */
    SEARCH_RESPONSE(3),
    /**
     * <code>UPLOAD_REQUEST = 4;</code>
     */
    UPLOAD_REQUEST(4),
    /**
     * <code>UPLOAD_RESPONSE = 5;</code>
     */
    UPLOAD_RESPONSE(5),
    /**
     * <code>REPLICATE_REQUEST = 6;</code>
     */
    REPLICATE_REQUEST(6),
    /**
     * <code>REPLICATE_RESPONSE = 7;</code>
     */
    REPLICATE_RESPONSE(7),
    /**
     * <code>CHUNK_REQUEST = 8;</code>
     */
    CHUNK_REQUEST(8),
    /**
     * <code>CHUNK_RESPONSE = 9;</code>
     */
    CHUNK_RESPONSE(9),
    /**
     * <code>DOWNLOAD_REQUEST = 10;</code>
     */
    DOWNLOAD_REQUEST(10),
    /**
     * <code>DOWNLOAD_RESPONSE = 11;</code>
     */
    DOWNLOAD_RESPONSE(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOCAL_SEARCH_REQUEST = 0;</code>
     */
    public static final int LOCAL_SEARCH_REQUEST_VALUE = 0;
    /**
     * <code>LOCAL_SEARCH_RESPONSE = 1;</code>
     */
    public static final int LOCAL_SEARCH_RESPONSE_VALUE = 1;
    /**
     * <code>SEARCH_REQUEST = 2;</code>
     */
    public static final int SEARCH_REQUEST_VALUE = 2;
    /**
     * <code>SEARCH_RESPONSE = 3;</code>
     */
    public static final int SEARCH_RESPONSE_VALUE = 3;
    /**
     * <code>UPLOAD_REQUEST = 4;</code>
     */
    public static final int UPLOAD_REQUEST_VALUE = 4;
    /**
     * <code>UPLOAD_RESPONSE = 5;</code>
     */
    public static final int UPLOAD_RESPONSE_VALUE = 5;
    /**
     * <code>REPLICATE_REQUEST = 6;</code>
     */
    public static final int REPLICATE_REQUEST_VALUE = 6;
    /**
     * <code>REPLICATE_RESPONSE = 7;</code>
     */
    public static final int REPLICATE_RESPONSE_VALUE = 7;
    /**
     * <code>CHUNK_REQUEST = 8;</code>
     */
    public static final int CHUNK_REQUEST_VALUE = 8;
    /**
     * <code>CHUNK_RESPONSE = 9;</code>
     */
    public static final int CHUNK_RESPONSE_VALUE = 9;
    /**
     * <code>DOWNLOAD_REQUEST = 10;</code>
     */
    public static final int DOWNLOAD_REQUEST_VALUE = 10;
    /**
     * <code>DOWNLOAD_RESPONSE = 11;</code>
     */
    public static final int DOWNLOAD_RESPONSE_VALUE = 11;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return LOCAL_SEARCH_REQUEST;
        case 1: return LOCAL_SEARCH_RESPONSE;
        case 2: return SEARCH_REQUEST;
        case 3: return SEARCH_RESPONSE;
        case 4: return UPLOAD_REQUEST;
        case 5: return UPLOAD_RESPONSE;
        case 6: return REPLICATE_REQUEST;
        case 7: return REPLICATE_RESPONSE;
        case 8: return CHUNK_REQUEST;
        case 9: return CHUNK_RESPONSE;
        case 10: return DOWNLOAD_REQUEST;
        case 11: return DOWNLOAD_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return entities.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Message.Type)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.Message.Type type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.Message.Type type = 1;</code>
   */
  public entities.Message.Type getType() {
    entities.Message.Type result = entities.Message.Type.valueOf(type_);
    return result == null ? entities.Message.Type.UNRECOGNIZED : result;
  }

  public static final int LOCALSEARCHREQUEST_FIELD_NUMBER = 2;
  private entities.LocalSearchRequest localSearchRequest_;
  /**
   * <code>.LocalSearchRequest localSearchRequest = 2;</code>
   */
  public boolean hasLocalSearchRequest() {
    return localSearchRequest_ != null;
  }
  /**
   * <code>.LocalSearchRequest localSearchRequest = 2;</code>
   */
  public entities.LocalSearchRequest getLocalSearchRequest() {
    return localSearchRequest_ == null ? entities.LocalSearchRequest.getDefaultInstance() : localSearchRequest_;
  }
  /**
   * <code>.LocalSearchRequest localSearchRequest = 2;</code>
   */
  public entities.LocalSearchRequestOrBuilder getLocalSearchRequestOrBuilder() {
    return getLocalSearchRequest();
  }

  public static final int LOCALSEARCHRESPONSE_FIELD_NUMBER = 3;
  private entities.LocalSearchResponse localSearchResponse_;
  /**
   * <code>.LocalSearchResponse localSearchResponse = 3;</code>
   */
  public boolean hasLocalSearchResponse() {
    return localSearchResponse_ != null;
  }
  /**
   * <code>.LocalSearchResponse localSearchResponse = 3;</code>
   */
  public entities.LocalSearchResponse getLocalSearchResponse() {
    return localSearchResponse_ == null ? entities.LocalSearchResponse.getDefaultInstance() : localSearchResponse_;
  }
  /**
   * <code>.LocalSearchResponse localSearchResponse = 3;</code>
   */
  public entities.LocalSearchResponseOrBuilder getLocalSearchResponseOrBuilder() {
    return getLocalSearchResponse();
  }

  public static final int SEARCHREQUEST_FIELD_NUMBER = 4;
  private entities.SearchRequest searchRequest_;
  /**
   * <code>.SearchRequest searchRequest = 4;</code>
   */
  public boolean hasSearchRequest() {
    return searchRequest_ != null;
  }
  /**
   * <code>.SearchRequest searchRequest = 4;</code>
   */
  public entities.SearchRequest getSearchRequest() {
    return searchRequest_ == null ? entities.SearchRequest.getDefaultInstance() : searchRequest_;
  }
  /**
   * <code>.SearchRequest searchRequest = 4;</code>
   */
  public entities.SearchRequestOrBuilder getSearchRequestOrBuilder() {
    return getSearchRequest();
  }

  public static final int SEARCHRESPONSE_FIELD_NUMBER = 5;
  private entities.SearchResponse searchResponse_;
  /**
   * <code>.SearchResponse searchResponse = 5;</code>
   */
  public boolean hasSearchResponse() {
    return searchResponse_ != null;
  }
  /**
   * <code>.SearchResponse searchResponse = 5;</code>
   */
  public entities.SearchResponse getSearchResponse() {
    return searchResponse_ == null ? entities.SearchResponse.getDefaultInstance() : searchResponse_;
  }
  /**
   * <code>.SearchResponse searchResponse = 5;</code>
   */
  public entities.SearchResponseOrBuilder getSearchResponseOrBuilder() {
    return getSearchResponse();
  }

  public static final int UPLOADREQUEST_FIELD_NUMBER = 6;
  private entities.UploadRequest uploadRequest_;
  /**
   * <code>.UploadRequest uploadRequest = 6;</code>
   */
  public boolean hasUploadRequest() {
    return uploadRequest_ != null;
  }
  /**
   * <code>.UploadRequest uploadRequest = 6;</code>
   */
  public entities.UploadRequest getUploadRequest() {
    return uploadRequest_ == null ? entities.UploadRequest.getDefaultInstance() : uploadRequest_;
  }
  /**
   * <code>.UploadRequest uploadRequest = 6;</code>
   */
  public entities.UploadRequestOrBuilder getUploadRequestOrBuilder() {
    return getUploadRequest();
  }

  public static final int UPLOADRESPONSE_FIELD_NUMBER = 7;
  private entities.UploadResponse uploadResponse_;
  /**
   * <code>.UploadResponse uploadResponse = 7;</code>
   */
  public boolean hasUploadResponse() {
    return uploadResponse_ != null;
  }
  /**
   * <code>.UploadResponse uploadResponse = 7;</code>
   */
  public entities.UploadResponse getUploadResponse() {
    return uploadResponse_ == null ? entities.UploadResponse.getDefaultInstance() : uploadResponse_;
  }
  /**
   * <code>.UploadResponse uploadResponse = 7;</code>
   */
  public entities.UploadResponseOrBuilder getUploadResponseOrBuilder() {
    return getUploadResponse();
  }

  public static final int REPLICATEREQUEST_FIELD_NUMBER = 8;
  private entities.ReplicateRequest replicateRequest_;
  /**
   * <code>.ReplicateRequest replicateRequest = 8;</code>
   */
  public boolean hasReplicateRequest() {
    return replicateRequest_ != null;
  }
  /**
   * <code>.ReplicateRequest replicateRequest = 8;</code>
   */
  public entities.ReplicateRequest getReplicateRequest() {
    return replicateRequest_ == null ? entities.ReplicateRequest.getDefaultInstance() : replicateRequest_;
  }
  /**
   * <code>.ReplicateRequest replicateRequest = 8;</code>
   */
  public entities.ReplicateRequestOrBuilder getReplicateRequestOrBuilder() {
    return getReplicateRequest();
  }

  public static final int REPLICATERESPONSE_FIELD_NUMBER = 9;
  private entities.ReplicateResponse replicateResponse_;
  /**
   * <code>.ReplicateResponse replicateResponse = 9;</code>
   */
  public boolean hasReplicateResponse() {
    return replicateResponse_ != null;
  }
  /**
   * <code>.ReplicateResponse replicateResponse = 9;</code>
   */
  public entities.ReplicateResponse getReplicateResponse() {
    return replicateResponse_ == null ? entities.ReplicateResponse.getDefaultInstance() : replicateResponse_;
  }
  /**
   * <code>.ReplicateResponse replicateResponse = 9;</code>
   */
  public entities.ReplicateResponseOrBuilder getReplicateResponseOrBuilder() {
    return getReplicateResponse();
  }

  public static final int CHUNKREQUEST_FIELD_NUMBER = 10;
  private entities.ChunkRequest chunkRequest_;
  /**
   * <code>.ChunkRequest chunkRequest = 10;</code>
   */
  public boolean hasChunkRequest() {
    return chunkRequest_ != null;
  }
  /**
   * <code>.ChunkRequest chunkRequest = 10;</code>
   */
  public entities.ChunkRequest getChunkRequest() {
    return chunkRequest_ == null ? entities.ChunkRequest.getDefaultInstance() : chunkRequest_;
  }
  /**
   * <code>.ChunkRequest chunkRequest = 10;</code>
   */
  public entities.ChunkRequestOrBuilder getChunkRequestOrBuilder() {
    return getChunkRequest();
  }

  public static final int CHUNKRESPONSE_FIELD_NUMBER = 11;
  private entities.ChunkResponse chunkResponse_;
  /**
   * <code>.ChunkResponse chunkResponse = 11;</code>
   */
  public boolean hasChunkResponse() {
    return chunkResponse_ != null;
  }
  /**
   * <code>.ChunkResponse chunkResponse = 11;</code>
   */
  public entities.ChunkResponse getChunkResponse() {
    return chunkResponse_ == null ? entities.ChunkResponse.getDefaultInstance() : chunkResponse_;
  }
  /**
   * <code>.ChunkResponse chunkResponse = 11;</code>
   */
  public entities.ChunkResponseOrBuilder getChunkResponseOrBuilder() {
    return getChunkResponse();
  }

  public static final int DOWNLOADREQUEST_FIELD_NUMBER = 12;
  private entities.DownloadRequest downloadRequest_;
  /**
   * <code>.DownloadRequest downloadRequest = 12;</code>
   */
  public boolean hasDownloadRequest() {
    return downloadRequest_ != null;
  }
  /**
   * <code>.DownloadRequest downloadRequest = 12;</code>
   */
  public entities.DownloadRequest getDownloadRequest() {
    return downloadRequest_ == null ? entities.DownloadRequest.getDefaultInstance() : downloadRequest_;
  }
  /**
   * <code>.DownloadRequest downloadRequest = 12;</code>
   */
  public entities.DownloadRequestOrBuilder getDownloadRequestOrBuilder() {
    return getDownloadRequest();
  }

  public static final int DOWNLOADRESPONSE_FIELD_NUMBER = 13;
  private entities.DownloadResponse downloadResponse_;
  /**
   * <code>.DownloadResponse downloadResponse = 13;</code>
   */
  public boolean hasDownloadResponse() {
    return downloadResponse_ != null;
  }
  /**
   * <code>.DownloadResponse downloadResponse = 13;</code>
   */
  public entities.DownloadResponse getDownloadResponse() {
    return downloadResponse_ == null ? entities.DownloadResponse.getDefaultInstance() : downloadResponse_;
  }
  /**
   * <code>.DownloadResponse downloadResponse = 13;</code>
   */
  public entities.DownloadResponseOrBuilder getDownloadResponseOrBuilder() {
    return getDownloadResponse();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != entities.Message.Type.LOCAL_SEARCH_REQUEST.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (localSearchRequest_ != null) {
      output.writeMessage(2, getLocalSearchRequest());
    }
    if (localSearchResponse_ != null) {
      output.writeMessage(3, getLocalSearchResponse());
    }
    if (searchRequest_ != null) {
      output.writeMessage(4, getSearchRequest());
    }
    if (searchResponse_ != null) {
      output.writeMessage(5, getSearchResponse());
    }
    if (uploadRequest_ != null) {
      output.writeMessage(6, getUploadRequest());
    }
    if (uploadResponse_ != null) {
      output.writeMessage(7, getUploadResponse());
    }
    if (replicateRequest_ != null) {
      output.writeMessage(8, getReplicateRequest());
    }
    if (replicateResponse_ != null) {
      output.writeMessage(9, getReplicateResponse());
    }
    if (chunkRequest_ != null) {
      output.writeMessage(10, getChunkRequest());
    }
    if (chunkResponse_ != null) {
      output.writeMessage(11, getChunkResponse());
    }
    if (downloadRequest_ != null) {
      output.writeMessage(12, getDownloadRequest());
    }
    if (downloadResponse_ != null) {
      output.writeMessage(13, getDownloadResponse());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != entities.Message.Type.LOCAL_SEARCH_REQUEST.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (localSearchRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLocalSearchRequest());
    }
    if (localSearchResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLocalSearchResponse());
    }
    if (searchRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSearchRequest());
    }
    if (searchResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSearchResponse());
    }
    if (uploadRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getUploadRequest());
    }
    if (uploadResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getUploadResponse());
    }
    if (replicateRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getReplicateRequest());
    }
    if (replicateResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getReplicateResponse());
    }
    if (chunkRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getChunkRequest());
    }
    if (chunkResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getChunkResponse());
    }
    if (downloadRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getDownloadRequest());
    }
    if (downloadResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getDownloadResponse());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof entities.Message)) {
      return super.equals(obj);
    }
    entities.Message other = (entities.Message) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && (hasLocalSearchRequest() == other.hasLocalSearchRequest());
    if (hasLocalSearchRequest()) {
      result = result && getLocalSearchRequest()
          .equals(other.getLocalSearchRequest());
    }
    result = result && (hasLocalSearchResponse() == other.hasLocalSearchResponse());
    if (hasLocalSearchResponse()) {
      result = result && getLocalSearchResponse()
          .equals(other.getLocalSearchResponse());
    }
    result = result && (hasSearchRequest() == other.hasSearchRequest());
    if (hasSearchRequest()) {
      result = result && getSearchRequest()
          .equals(other.getSearchRequest());
    }
    result = result && (hasSearchResponse() == other.hasSearchResponse());
    if (hasSearchResponse()) {
      result = result && getSearchResponse()
          .equals(other.getSearchResponse());
    }
    result = result && (hasUploadRequest() == other.hasUploadRequest());
    if (hasUploadRequest()) {
      result = result && getUploadRequest()
          .equals(other.getUploadRequest());
    }
    result = result && (hasUploadResponse() == other.hasUploadResponse());
    if (hasUploadResponse()) {
      result = result && getUploadResponse()
          .equals(other.getUploadResponse());
    }
    result = result && (hasReplicateRequest() == other.hasReplicateRequest());
    if (hasReplicateRequest()) {
      result = result && getReplicateRequest()
          .equals(other.getReplicateRequest());
    }
    result = result && (hasReplicateResponse() == other.hasReplicateResponse());
    if (hasReplicateResponse()) {
      result = result && getReplicateResponse()
          .equals(other.getReplicateResponse());
    }
    result = result && (hasChunkRequest() == other.hasChunkRequest());
    if (hasChunkRequest()) {
      result = result && getChunkRequest()
          .equals(other.getChunkRequest());
    }
    result = result && (hasChunkResponse() == other.hasChunkResponse());
    if (hasChunkResponse()) {
      result = result && getChunkResponse()
          .equals(other.getChunkResponse());
    }
    result = result && (hasDownloadRequest() == other.hasDownloadRequest());
    if (hasDownloadRequest()) {
      result = result && getDownloadRequest()
          .equals(other.getDownloadRequest());
    }
    result = result && (hasDownloadResponse() == other.hasDownloadResponse());
    if (hasDownloadResponse()) {
      result = result && getDownloadResponse()
          .equals(other.getDownloadResponse());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasLocalSearchRequest()) {
      hash = (37 * hash) + LOCALSEARCHREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getLocalSearchRequest().hashCode();
    }
    if (hasLocalSearchResponse()) {
      hash = (37 * hash) + LOCALSEARCHRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getLocalSearchResponse().hashCode();
    }
    if (hasSearchRequest()) {
      hash = (37 * hash) + SEARCHREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getSearchRequest().hashCode();
    }
    if (hasSearchResponse()) {
      hash = (37 * hash) + SEARCHRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getSearchResponse().hashCode();
    }
    if (hasUploadRequest()) {
      hash = (37 * hash) + UPLOADREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getUploadRequest().hashCode();
    }
    if (hasUploadResponse()) {
      hash = (37 * hash) + UPLOADRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getUploadResponse().hashCode();
    }
    if (hasReplicateRequest()) {
      hash = (37 * hash) + REPLICATEREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getReplicateRequest().hashCode();
    }
    if (hasReplicateResponse()) {
      hash = (37 * hash) + REPLICATERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getReplicateResponse().hashCode();
    }
    if (hasChunkRequest()) {
      hash = (37 * hash) + CHUNKREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getChunkRequest().hashCode();
    }
    if (hasChunkResponse()) {
      hash = (37 * hash) + CHUNKRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getChunkResponse().hashCode();
    }
    if (hasDownloadRequest()) {
      hash = (37 * hash) + DOWNLOADREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getDownloadRequest().hashCode();
    }
    if (hasDownloadResponse()) {
      hash = (37 * hash) + DOWNLOADRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getDownloadResponse().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static entities.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static entities.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static entities.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static entities.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static entities.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static entities.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static entities.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static entities.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static entities.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static entities.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static entities.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static entities.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(entities.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Wrapper message
   * </pre>
   *
   * Protobuf type {@code Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message)
      entities.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return entities.Torr.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return entities.Torr.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              entities.Message.class, entities.Message.Builder.class);
    }

    // Construct using entities.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (localSearchRequestBuilder_ == null) {
        localSearchRequest_ = null;
      } else {
        localSearchRequest_ = null;
        localSearchRequestBuilder_ = null;
      }
      if (localSearchResponseBuilder_ == null) {
        localSearchResponse_ = null;
      } else {
        localSearchResponse_ = null;
        localSearchResponseBuilder_ = null;
      }
      if (searchRequestBuilder_ == null) {
        searchRequest_ = null;
      } else {
        searchRequest_ = null;
        searchRequestBuilder_ = null;
      }
      if (searchResponseBuilder_ == null) {
        searchResponse_ = null;
      } else {
        searchResponse_ = null;
        searchResponseBuilder_ = null;
      }
      if (uploadRequestBuilder_ == null) {
        uploadRequest_ = null;
      } else {
        uploadRequest_ = null;
        uploadRequestBuilder_ = null;
      }
      if (uploadResponseBuilder_ == null) {
        uploadResponse_ = null;
      } else {
        uploadResponse_ = null;
        uploadResponseBuilder_ = null;
      }
      if (replicateRequestBuilder_ == null) {
        replicateRequest_ = null;
      } else {
        replicateRequest_ = null;
        replicateRequestBuilder_ = null;
      }
      if (replicateResponseBuilder_ == null) {
        replicateResponse_ = null;
      } else {
        replicateResponse_ = null;
        replicateResponseBuilder_ = null;
      }
      if (chunkRequestBuilder_ == null) {
        chunkRequest_ = null;
      } else {
        chunkRequest_ = null;
        chunkRequestBuilder_ = null;
      }
      if (chunkResponseBuilder_ == null) {
        chunkResponse_ = null;
      } else {
        chunkResponse_ = null;
        chunkResponseBuilder_ = null;
      }
      if (downloadRequestBuilder_ == null) {
        downloadRequest_ = null;
      } else {
        downloadRequest_ = null;
        downloadRequestBuilder_ = null;
      }
      if (downloadResponseBuilder_ == null) {
        downloadResponse_ = null;
      } else {
        downloadResponse_ = null;
        downloadResponseBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return entities.Torr.internal_static_Message_descriptor;
    }

    public entities.Message getDefaultInstanceForType() {
      return entities.Message.getDefaultInstance();
    }

    public entities.Message build() {
      entities.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public entities.Message buildPartial() {
      entities.Message result = new entities.Message(this);
      result.type_ = type_;
      if (localSearchRequestBuilder_ == null) {
        result.localSearchRequest_ = localSearchRequest_;
      } else {
        result.localSearchRequest_ = localSearchRequestBuilder_.build();
      }
      if (localSearchResponseBuilder_ == null) {
        result.localSearchResponse_ = localSearchResponse_;
      } else {
        result.localSearchResponse_ = localSearchResponseBuilder_.build();
      }
      if (searchRequestBuilder_ == null) {
        result.searchRequest_ = searchRequest_;
      } else {
        result.searchRequest_ = searchRequestBuilder_.build();
      }
      if (searchResponseBuilder_ == null) {
        result.searchResponse_ = searchResponse_;
      } else {
        result.searchResponse_ = searchResponseBuilder_.build();
      }
      if (uploadRequestBuilder_ == null) {
        result.uploadRequest_ = uploadRequest_;
      } else {
        result.uploadRequest_ = uploadRequestBuilder_.build();
      }
      if (uploadResponseBuilder_ == null) {
        result.uploadResponse_ = uploadResponse_;
      } else {
        result.uploadResponse_ = uploadResponseBuilder_.build();
      }
      if (replicateRequestBuilder_ == null) {
        result.replicateRequest_ = replicateRequest_;
      } else {
        result.replicateRequest_ = replicateRequestBuilder_.build();
      }
      if (replicateResponseBuilder_ == null) {
        result.replicateResponse_ = replicateResponse_;
      } else {
        result.replicateResponse_ = replicateResponseBuilder_.build();
      }
      if (chunkRequestBuilder_ == null) {
        result.chunkRequest_ = chunkRequest_;
      } else {
        result.chunkRequest_ = chunkRequestBuilder_.build();
      }
      if (chunkResponseBuilder_ == null) {
        result.chunkResponse_ = chunkResponse_;
      } else {
        result.chunkResponse_ = chunkResponseBuilder_.build();
      }
      if (downloadRequestBuilder_ == null) {
        result.downloadRequest_ = downloadRequest_;
      } else {
        result.downloadRequest_ = downloadRequestBuilder_.build();
      }
      if (downloadResponseBuilder_ == null) {
        result.downloadResponse_ = downloadResponse_;
      } else {
        result.downloadResponse_ = downloadResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof entities.Message) {
        return mergeFrom((entities.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(entities.Message other) {
      if (other == entities.Message.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasLocalSearchRequest()) {
        mergeLocalSearchRequest(other.getLocalSearchRequest());
      }
      if (other.hasLocalSearchResponse()) {
        mergeLocalSearchResponse(other.getLocalSearchResponse());
      }
      if (other.hasSearchRequest()) {
        mergeSearchRequest(other.getSearchRequest());
      }
      if (other.hasSearchResponse()) {
        mergeSearchResponse(other.getSearchResponse());
      }
      if (other.hasUploadRequest()) {
        mergeUploadRequest(other.getUploadRequest());
      }
      if (other.hasUploadResponse()) {
        mergeUploadResponse(other.getUploadResponse());
      }
      if (other.hasReplicateRequest()) {
        mergeReplicateRequest(other.getReplicateRequest());
      }
      if (other.hasReplicateResponse()) {
        mergeReplicateResponse(other.getReplicateResponse());
      }
      if (other.hasChunkRequest()) {
        mergeChunkRequest(other.getChunkRequest());
      }
      if (other.hasChunkResponse()) {
        mergeChunkResponse(other.getChunkResponse());
      }
      if (other.hasDownloadRequest()) {
        mergeDownloadRequest(other.getDownloadRequest());
      }
      if (other.hasDownloadResponse()) {
        mergeDownloadResponse(other.getDownloadResponse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      entities.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (entities.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.Message.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Message.Type type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Message.Type type = 1;</code>
     */
    public entities.Message.Type getType() {
      entities.Message.Type result = entities.Message.Type.valueOf(type_);
      return result == null ? entities.Message.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.Message.Type type = 1;</code>
     */
    public Builder setType(entities.Message.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Message.Type type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private entities.LocalSearchRequest localSearchRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.LocalSearchRequest, entities.LocalSearchRequest.Builder, entities.LocalSearchRequestOrBuilder> localSearchRequestBuilder_;
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public boolean hasLocalSearchRequest() {
      return localSearchRequestBuilder_ != null || localSearchRequest_ != null;
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public entities.LocalSearchRequest getLocalSearchRequest() {
      if (localSearchRequestBuilder_ == null) {
        return localSearchRequest_ == null ? entities.LocalSearchRequest.getDefaultInstance() : localSearchRequest_;
      } else {
        return localSearchRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public Builder setLocalSearchRequest(entities.LocalSearchRequest value) {
      if (localSearchRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        localSearchRequest_ = value;
        onChanged();
      } else {
        localSearchRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public Builder setLocalSearchRequest(
        entities.LocalSearchRequest.Builder builderForValue) {
      if (localSearchRequestBuilder_ == null) {
        localSearchRequest_ = builderForValue.build();
        onChanged();
      } else {
        localSearchRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public Builder mergeLocalSearchRequest(entities.LocalSearchRequest value) {
      if (localSearchRequestBuilder_ == null) {
        if (localSearchRequest_ != null) {
          localSearchRequest_ =
            entities.LocalSearchRequest.newBuilder(localSearchRequest_).mergeFrom(value).buildPartial();
        } else {
          localSearchRequest_ = value;
        }
        onChanged();
      } else {
        localSearchRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public Builder clearLocalSearchRequest() {
      if (localSearchRequestBuilder_ == null) {
        localSearchRequest_ = null;
        onChanged();
      } else {
        localSearchRequest_ = null;
        localSearchRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public entities.LocalSearchRequest.Builder getLocalSearchRequestBuilder() {
      
      onChanged();
      return getLocalSearchRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    public entities.LocalSearchRequestOrBuilder getLocalSearchRequestOrBuilder() {
      if (localSearchRequestBuilder_ != null) {
        return localSearchRequestBuilder_.getMessageOrBuilder();
      } else {
        return localSearchRequest_ == null ?
            entities.LocalSearchRequest.getDefaultInstance() : localSearchRequest_;
      }
    }
    /**
     * <code>.LocalSearchRequest localSearchRequest = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.LocalSearchRequest, entities.LocalSearchRequest.Builder, entities.LocalSearchRequestOrBuilder> 
        getLocalSearchRequestFieldBuilder() {
      if (localSearchRequestBuilder_ == null) {
        localSearchRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.LocalSearchRequest, entities.LocalSearchRequest.Builder, entities.LocalSearchRequestOrBuilder>(
                getLocalSearchRequest(),
                getParentForChildren(),
                isClean());
        localSearchRequest_ = null;
      }
      return localSearchRequestBuilder_;
    }

    private entities.LocalSearchResponse localSearchResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.LocalSearchResponse, entities.LocalSearchResponse.Builder, entities.LocalSearchResponseOrBuilder> localSearchResponseBuilder_;
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public boolean hasLocalSearchResponse() {
      return localSearchResponseBuilder_ != null || localSearchResponse_ != null;
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public entities.LocalSearchResponse getLocalSearchResponse() {
      if (localSearchResponseBuilder_ == null) {
        return localSearchResponse_ == null ? entities.LocalSearchResponse.getDefaultInstance() : localSearchResponse_;
      } else {
        return localSearchResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public Builder setLocalSearchResponse(entities.LocalSearchResponse value) {
      if (localSearchResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        localSearchResponse_ = value;
        onChanged();
      } else {
        localSearchResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public Builder setLocalSearchResponse(
        entities.LocalSearchResponse.Builder builderForValue) {
      if (localSearchResponseBuilder_ == null) {
        localSearchResponse_ = builderForValue.build();
        onChanged();
      } else {
        localSearchResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public Builder mergeLocalSearchResponse(entities.LocalSearchResponse value) {
      if (localSearchResponseBuilder_ == null) {
        if (localSearchResponse_ != null) {
          localSearchResponse_ =
            entities.LocalSearchResponse.newBuilder(localSearchResponse_).mergeFrom(value).buildPartial();
        } else {
          localSearchResponse_ = value;
        }
        onChanged();
      } else {
        localSearchResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public Builder clearLocalSearchResponse() {
      if (localSearchResponseBuilder_ == null) {
        localSearchResponse_ = null;
        onChanged();
      } else {
        localSearchResponse_ = null;
        localSearchResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public entities.LocalSearchResponse.Builder getLocalSearchResponseBuilder() {
      
      onChanged();
      return getLocalSearchResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    public entities.LocalSearchResponseOrBuilder getLocalSearchResponseOrBuilder() {
      if (localSearchResponseBuilder_ != null) {
        return localSearchResponseBuilder_.getMessageOrBuilder();
      } else {
        return localSearchResponse_ == null ?
            entities.LocalSearchResponse.getDefaultInstance() : localSearchResponse_;
      }
    }
    /**
     * <code>.LocalSearchResponse localSearchResponse = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.LocalSearchResponse, entities.LocalSearchResponse.Builder, entities.LocalSearchResponseOrBuilder> 
        getLocalSearchResponseFieldBuilder() {
      if (localSearchResponseBuilder_ == null) {
        localSearchResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.LocalSearchResponse, entities.LocalSearchResponse.Builder, entities.LocalSearchResponseOrBuilder>(
                getLocalSearchResponse(),
                getParentForChildren(),
                isClean());
        localSearchResponse_ = null;
      }
      return localSearchResponseBuilder_;
    }

    private entities.SearchRequest searchRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.SearchRequest, entities.SearchRequest.Builder, entities.SearchRequestOrBuilder> searchRequestBuilder_;
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public boolean hasSearchRequest() {
      return searchRequestBuilder_ != null || searchRequest_ != null;
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public entities.SearchRequest getSearchRequest() {
      if (searchRequestBuilder_ == null) {
        return searchRequest_ == null ? entities.SearchRequest.getDefaultInstance() : searchRequest_;
      } else {
        return searchRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public Builder setSearchRequest(entities.SearchRequest value) {
      if (searchRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        searchRequest_ = value;
        onChanged();
      } else {
        searchRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public Builder setSearchRequest(
        entities.SearchRequest.Builder builderForValue) {
      if (searchRequestBuilder_ == null) {
        searchRequest_ = builderForValue.build();
        onChanged();
      } else {
        searchRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public Builder mergeSearchRequest(entities.SearchRequest value) {
      if (searchRequestBuilder_ == null) {
        if (searchRequest_ != null) {
          searchRequest_ =
            entities.SearchRequest.newBuilder(searchRequest_).mergeFrom(value).buildPartial();
        } else {
          searchRequest_ = value;
        }
        onChanged();
      } else {
        searchRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public Builder clearSearchRequest() {
      if (searchRequestBuilder_ == null) {
        searchRequest_ = null;
        onChanged();
      } else {
        searchRequest_ = null;
        searchRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public entities.SearchRequest.Builder getSearchRequestBuilder() {
      
      onChanged();
      return getSearchRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    public entities.SearchRequestOrBuilder getSearchRequestOrBuilder() {
      if (searchRequestBuilder_ != null) {
        return searchRequestBuilder_.getMessageOrBuilder();
      } else {
        return searchRequest_ == null ?
            entities.SearchRequest.getDefaultInstance() : searchRequest_;
      }
    }
    /**
     * <code>.SearchRequest searchRequest = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.SearchRequest, entities.SearchRequest.Builder, entities.SearchRequestOrBuilder> 
        getSearchRequestFieldBuilder() {
      if (searchRequestBuilder_ == null) {
        searchRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.SearchRequest, entities.SearchRequest.Builder, entities.SearchRequestOrBuilder>(
                getSearchRequest(),
                getParentForChildren(),
                isClean());
        searchRequest_ = null;
      }
      return searchRequestBuilder_;
    }

    private entities.SearchResponse searchResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.SearchResponse, entities.SearchResponse.Builder, entities.SearchResponseOrBuilder> searchResponseBuilder_;
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public boolean hasSearchResponse() {
      return searchResponseBuilder_ != null || searchResponse_ != null;
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public entities.SearchResponse getSearchResponse() {
      if (searchResponseBuilder_ == null) {
        return searchResponse_ == null ? entities.SearchResponse.getDefaultInstance() : searchResponse_;
      } else {
        return searchResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public Builder setSearchResponse(entities.SearchResponse value) {
      if (searchResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        searchResponse_ = value;
        onChanged();
      } else {
        searchResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public Builder setSearchResponse(
        entities.SearchResponse.Builder builderForValue) {
      if (searchResponseBuilder_ == null) {
        searchResponse_ = builderForValue.build();
        onChanged();
      } else {
        searchResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public Builder mergeSearchResponse(entities.SearchResponse value) {
      if (searchResponseBuilder_ == null) {
        if (searchResponse_ != null) {
          searchResponse_ =
            entities.SearchResponse.newBuilder(searchResponse_).mergeFrom(value).buildPartial();
        } else {
          searchResponse_ = value;
        }
        onChanged();
      } else {
        searchResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public Builder clearSearchResponse() {
      if (searchResponseBuilder_ == null) {
        searchResponse_ = null;
        onChanged();
      } else {
        searchResponse_ = null;
        searchResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public entities.SearchResponse.Builder getSearchResponseBuilder() {
      
      onChanged();
      return getSearchResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    public entities.SearchResponseOrBuilder getSearchResponseOrBuilder() {
      if (searchResponseBuilder_ != null) {
        return searchResponseBuilder_.getMessageOrBuilder();
      } else {
        return searchResponse_ == null ?
            entities.SearchResponse.getDefaultInstance() : searchResponse_;
      }
    }
    /**
     * <code>.SearchResponse searchResponse = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.SearchResponse, entities.SearchResponse.Builder, entities.SearchResponseOrBuilder> 
        getSearchResponseFieldBuilder() {
      if (searchResponseBuilder_ == null) {
        searchResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.SearchResponse, entities.SearchResponse.Builder, entities.SearchResponseOrBuilder>(
                getSearchResponse(),
                getParentForChildren(),
                isClean());
        searchResponse_ = null;
      }
      return searchResponseBuilder_;
    }

    private entities.UploadRequest uploadRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.UploadRequest, entities.UploadRequest.Builder, entities.UploadRequestOrBuilder> uploadRequestBuilder_;
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public boolean hasUploadRequest() {
      return uploadRequestBuilder_ != null || uploadRequest_ != null;
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public entities.UploadRequest getUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        return uploadRequest_ == null ? entities.UploadRequest.getDefaultInstance() : uploadRequest_;
      } else {
        return uploadRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public Builder setUploadRequest(entities.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        uploadRequest_ = value;
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public Builder setUploadRequest(
        entities.UploadRequest.Builder builderForValue) {
      if (uploadRequestBuilder_ == null) {
        uploadRequest_ = builderForValue.build();
        onChanged();
      } else {
        uploadRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public Builder mergeUploadRequest(entities.UploadRequest value) {
      if (uploadRequestBuilder_ == null) {
        if (uploadRequest_ != null) {
          uploadRequest_ =
            entities.UploadRequest.newBuilder(uploadRequest_).mergeFrom(value).buildPartial();
        } else {
          uploadRequest_ = value;
        }
        onChanged();
      } else {
        uploadRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public Builder clearUploadRequest() {
      if (uploadRequestBuilder_ == null) {
        uploadRequest_ = null;
        onChanged();
      } else {
        uploadRequest_ = null;
        uploadRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public entities.UploadRequest.Builder getUploadRequestBuilder() {
      
      onChanged();
      return getUploadRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    public entities.UploadRequestOrBuilder getUploadRequestOrBuilder() {
      if (uploadRequestBuilder_ != null) {
        return uploadRequestBuilder_.getMessageOrBuilder();
      } else {
        return uploadRequest_ == null ?
            entities.UploadRequest.getDefaultInstance() : uploadRequest_;
      }
    }
    /**
     * <code>.UploadRequest uploadRequest = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.UploadRequest, entities.UploadRequest.Builder, entities.UploadRequestOrBuilder> 
        getUploadRequestFieldBuilder() {
      if (uploadRequestBuilder_ == null) {
        uploadRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.UploadRequest, entities.UploadRequest.Builder, entities.UploadRequestOrBuilder>(
                getUploadRequest(),
                getParentForChildren(),
                isClean());
        uploadRequest_ = null;
      }
      return uploadRequestBuilder_;
    }

    private entities.UploadResponse uploadResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.UploadResponse, entities.UploadResponse.Builder, entities.UploadResponseOrBuilder> uploadResponseBuilder_;
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public boolean hasUploadResponse() {
      return uploadResponseBuilder_ != null || uploadResponse_ != null;
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public entities.UploadResponse getUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        return uploadResponse_ == null ? entities.UploadResponse.getDefaultInstance() : uploadResponse_;
      } else {
        return uploadResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public Builder setUploadResponse(entities.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        uploadResponse_ = value;
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public Builder setUploadResponse(
        entities.UploadResponse.Builder builderForValue) {
      if (uploadResponseBuilder_ == null) {
        uploadResponse_ = builderForValue.build();
        onChanged();
      } else {
        uploadResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public Builder mergeUploadResponse(entities.UploadResponse value) {
      if (uploadResponseBuilder_ == null) {
        if (uploadResponse_ != null) {
          uploadResponse_ =
            entities.UploadResponse.newBuilder(uploadResponse_).mergeFrom(value).buildPartial();
        } else {
          uploadResponse_ = value;
        }
        onChanged();
      } else {
        uploadResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public Builder clearUploadResponse() {
      if (uploadResponseBuilder_ == null) {
        uploadResponse_ = null;
        onChanged();
      } else {
        uploadResponse_ = null;
        uploadResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public entities.UploadResponse.Builder getUploadResponseBuilder() {
      
      onChanged();
      return getUploadResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    public entities.UploadResponseOrBuilder getUploadResponseOrBuilder() {
      if (uploadResponseBuilder_ != null) {
        return uploadResponseBuilder_.getMessageOrBuilder();
      } else {
        return uploadResponse_ == null ?
            entities.UploadResponse.getDefaultInstance() : uploadResponse_;
      }
    }
    /**
     * <code>.UploadResponse uploadResponse = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.UploadResponse, entities.UploadResponse.Builder, entities.UploadResponseOrBuilder> 
        getUploadResponseFieldBuilder() {
      if (uploadResponseBuilder_ == null) {
        uploadResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.UploadResponse, entities.UploadResponse.Builder, entities.UploadResponseOrBuilder>(
                getUploadResponse(),
                getParentForChildren(),
                isClean());
        uploadResponse_ = null;
      }
      return uploadResponseBuilder_;
    }

    private entities.ReplicateRequest replicateRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ReplicateRequest, entities.ReplicateRequest.Builder, entities.ReplicateRequestOrBuilder> replicateRequestBuilder_;
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public boolean hasReplicateRequest() {
      return replicateRequestBuilder_ != null || replicateRequest_ != null;
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public entities.ReplicateRequest getReplicateRequest() {
      if (replicateRequestBuilder_ == null) {
        return replicateRequest_ == null ? entities.ReplicateRequest.getDefaultInstance() : replicateRequest_;
      } else {
        return replicateRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public Builder setReplicateRequest(entities.ReplicateRequest value) {
      if (replicateRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        replicateRequest_ = value;
        onChanged();
      } else {
        replicateRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public Builder setReplicateRequest(
        entities.ReplicateRequest.Builder builderForValue) {
      if (replicateRequestBuilder_ == null) {
        replicateRequest_ = builderForValue.build();
        onChanged();
      } else {
        replicateRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public Builder mergeReplicateRequest(entities.ReplicateRequest value) {
      if (replicateRequestBuilder_ == null) {
        if (replicateRequest_ != null) {
          replicateRequest_ =
            entities.ReplicateRequest.newBuilder(replicateRequest_).mergeFrom(value).buildPartial();
        } else {
          replicateRequest_ = value;
        }
        onChanged();
      } else {
        replicateRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public Builder clearReplicateRequest() {
      if (replicateRequestBuilder_ == null) {
        replicateRequest_ = null;
        onChanged();
      } else {
        replicateRequest_ = null;
        replicateRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public entities.ReplicateRequest.Builder getReplicateRequestBuilder() {
      
      onChanged();
      return getReplicateRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    public entities.ReplicateRequestOrBuilder getReplicateRequestOrBuilder() {
      if (replicateRequestBuilder_ != null) {
        return replicateRequestBuilder_.getMessageOrBuilder();
      } else {
        return replicateRequest_ == null ?
            entities.ReplicateRequest.getDefaultInstance() : replicateRequest_;
      }
    }
    /**
     * <code>.ReplicateRequest replicateRequest = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ReplicateRequest, entities.ReplicateRequest.Builder, entities.ReplicateRequestOrBuilder> 
        getReplicateRequestFieldBuilder() {
      if (replicateRequestBuilder_ == null) {
        replicateRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.ReplicateRequest, entities.ReplicateRequest.Builder, entities.ReplicateRequestOrBuilder>(
                getReplicateRequest(),
                getParentForChildren(),
                isClean());
        replicateRequest_ = null;
      }
      return replicateRequestBuilder_;
    }

    private entities.ReplicateResponse replicateResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ReplicateResponse, entities.ReplicateResponse.Builder, entities.ReplicateResponseOrBuilder> replicateResponseBuilder_;
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public boolean hasReplicateResponse() {
      return replicateResponseBuilder_ != null || replicateResponse_ != null;
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public entities.ReplicateResponse getReplicateResponse() {
      if (replicateResponseBuilder_ == null) {
        return replicateResponse_ == null ? entities.ReplicateResponse.getDefaultInstance() : replicateResponse_;
      } else {
        return replicateResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public Builder setReplicateResponse(entities.ReplicateResponse value) {
      if (replicateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        replicateResponse_ = value;
        onChanged();
      } else {
        replicateResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public Builder setReplicateResponse(
        entities.ReplicateResponse.Builder builderForValue) {
      if (replicateResponseBuilder_ == null) {
        replicateResponse_ = builderForValue.build();
        onChanged();
      } else {
        replicateResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public Builder mergeReplicateResponse(entities.ReplicateResponse value) {
      if (replicateResponseBuilder_ == null) {
        if (replicateResponse_ != null) {
          replicateResponse_ =
            entities.ReplicateResponse.newBuilder(replicateResponse_).mergeFrom(value).buildPartial();
        } else {
          replicateResponse_ = value;
        }
        onChanged();
      } else {
        replicateResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public Builder clearReplicateResponse() {
      if (replicateResponseBuilder_ == null) {
        replicateResponse_ = null;
        onChanged();
      } else {
        replicateResponse_ = null;
        replicateResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public entities.ReplicateResponse.Builder getReplicateResponseBuilder() {
      
      onChanged();
      return getReplicateResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    public entities.ReplicateResponseOrBuilder getReplicateResponseOrBuilder() {
      if (replicateResponseBuilder_ != null) {
        return replicateResponseBuilder_.getMessageOrBuilder();
      } else {
        return replicateResponse_ == null ?
            entities.ReplicateResponse.getDefaultInstance() : replicateResponse_;
      }
    }
    /**
     * <code>.ReplicateResponse replicateResponse = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ReplicateResponse, entities.ReplicateResponse.Builder, entities.ReplicateResponseOrBuilder> 
        getReplicateResponseFieldBuilder() {
      if (replicateResponseBuilder_ == null) {
        replicateResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.ReplicateResponse, entities.ReplicateResponse.Builder, entities.ReplicateResponseOrBuilder>(
                getReplicateResponse(),
                getParentForChildren(),
                isClean());
        replicateResponse_ = null;
      }
      return replicateResponseBuilder_;
    }

    private entities.ChunkRequest chunkRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ChunkRequest, entities.ChunkRequest.Builder, entities.ChunkRequestOrBuilder> chunkRequestBuilder_;
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public boolean hasChunkRequest() {
      return chunkRequestBuilder_ != null || chunkRequest_ != null;
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public entities.ChunkRequest getChunkRequest() {
      if (chunkRequestBuilder_ == null) {
        return chunkRequest_ == null ? entities.ChunkRequest.getDefaultInstance() : chunkRequest_;
      } else {
        return chunkRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public Builder setChunkRequest(entities.ChunkRequest value) {
      if (chunkRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chunkRequest_ = value;
        onChanged();
      } else {
        chunkRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public Builder setChunkRequest(
        entities.ChunkRequest.Builder builderForValue) {
      if (chunkRequestBuilder_ == null) {
        chunkRequest_ = builderForValue.build();
        onChanged();
      } else {
        chunkRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public Builder mergeChunkRequest(entities.ChunkRequest value) {
      if (chunkRequestBuilder_ == null) {
        if (chunkRequest_ != null) {
          chunkRequest_ =
            entities.ChunkRequest.newBuilder(chunkRequest_).mergeFrom(value).buildPartial();
        } else {
          chunkRequest_ = value;
        }
        onChanged();
      } else {
        chunkRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public Builder clearChunkRequest() {
      if (chunkRequestBuilder_ == null) {
        chunkRequest_ = null;
        onChanged();
      } else {
        chunkRequest_ = null;
        chunkRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public entities.ChunkRequest.Builder getChunkRequestBuilder() {
      
      onChanged();
      return getChunkRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    public entities.ChunkRequestOrBuilder getChunkRequestOrBuilder() {
      if (chunkRequestBuilder_ != null) {
        return chunkRequestBuilder_.getMessageOrBuilder();
      } else {
        return chunkRequest_ == null ?
            entities.ChunkRequest.getDefaultInstance() : chunkRequest_;
      }
    }
    /**
     * <code>.ChunkRequest chunkRequest = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ChunkRequest, entities.ChunkRequest.Builder, entities.ChunkRequestOrBuilder> 
        getChunkRequestFieldBuilder() {
      if (chunkRequestBuilder_ == null) {
        chunkRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.ChunkRequest, entities.ChunkRequest.Builder, entities.ChunkRequestOrBuilder>(
                getChunkRequest(),
                getParentForChildren(),
                isClean());
        chunkRequest_ = null;
      }
      return chunkRequestBuilder_;
    }

    private entities.ChunkResponse chunkResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ChunkResponse, entities.ChunkResponse.Builder, entities.ChunkResponseOrBuilder> chunkResponseBuilder_;
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public boolean hasChunkResponse() {
      return chunkResponseBuilder_ != null || chunkResponse_ != null;
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public entities.ChunkResponse getChunkResponse() {
      if (chunkResponseBuilder_ == null) {
        return chunkResponse_ == null ? entities.ChunkResponse.getDefaultInstance() : chunkResponse_;
      } else {
        return chunkResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public Builder setChunkResponse(entities.ChunkResponse value) {
      if (chunkResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chunkResponse_ = value;
        onChanged();
      } else {
        chunkResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public Builder setChunkResponse(
        entities.ChunkResponse.Builder builderForValue) {
      if (chunkResponseBuilder_ == null) {
        chunkResponse_ = builderForValue.build();
        onChanged();
      } else {
        chunkResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public Builder mergeChunkResponse(entities.ChunkResponse value) {
      if (chunkResponseBuilder_ == null) {
        if (chunkResponse_ != null) {
          chunkResponse_ =
            entities.ChunkResponse.newBuilder(chunkResponse_).mergeFrom(value).buildPartial();
        } else {
          chunkResponse_ = value;
        }
        onChanged();
      } else {
        chunkResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public Builder clearChunkResponse() {
      if (chunkResponseBuilder_ == null) {
        chunkResponse_ = null;
        onChanged();
      } else {
        chunkResponse_ = null;
        chunkResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public entities.ChunkResponse.Builder getChunkResponseBuilder() {
      
      onChanged();
      return getChunkResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    public entities.ChunkResponseOrBuilder getChunkResponseOrBuilder() {
      if (chunkResponseBuilder_ != null) {
        return chunkResponseBuilder_.getMessageOrBuilder();
      } else {
        return chunkResponse_ == null ?
            entities.ChunkResponse.getDefaultInstance() : chunkResponse_;
      }
    }
    /**
     * <code>.ChunkResponse chunkResponse = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.ChunkResponse, entities.ChunkResponse.Builder, entities.ChunkResponseOrBuilder> 
        getChunkResponseFieldBuilder() {
      if (chunkResponseBuilder_ == null) {
        chunkResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.ChunkResponse, entities.ChunkResponse.Builder, entities.ChunkResponseOrBuilder>(
                getChunkResponse(),
                getParentForChildren(),
                isClean());
        chunkResponse_ = null;
      }
      return chunkResponseBuilder_;
    }

    private entities.DownloadRequest downloadRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.DownloadRequest, entities.DownloadRequest.Builder, entities.DownloadRequestOrBuilder> downloadRequestBuilder_;
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public boolean hasDownloadRequest() {
      return downloadRequestBuilder_ != null || downloadRequest_ != null;
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public entities.DownloadRequest getDownloadRequest() {
      if (downloadRequestBuilder_ == null) {
        return downloadRequest_ == null ? entities.DownloadRequest.getDefaultInstance() : downloadRequest_;
      } else {
        return downloadRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public Builder setDownloadRequest(entities.DownloadRequest value) {
      if (downloadRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        downloadRequest_ = value;
        onChanged();
      } else {
        downloadRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public Builder setDownloadRequest(
        entities.DownloadRequest.Builder builderForValue) {
      if (downloadRequestBuilder_ == null) {
        downloadRequest_ = builderForValue.build();
        onChanged();
      } else {
        downloadRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public Builder mergeDownloadRequest(entities.DownloadRequest value) {
      if (downloadRequestBuilder_ == null) {
        if (downloadRequest_ != null) {
          downloadRequest_ =
            entities.DownloadRequest.newBuilder(downloadRequest_).mergeFrom(value).buildPartial();
        } else {
          downloadRequest_ = value;
        }
        onChanged();
      } else {
        downloadRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public Builder clearDownloadRequest() {
      if (downloadRequestBuilder_ == null) {
        downloadRequest_ = null;
        onChanged();
      } else {
        downloadRequest_ = null;
        downloadRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public entities.DownloadRequest.Builder getDownloadRequestBuilder() {
      
      onChanged();
      return getDownloadRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    public entities.DownloadRequestOrBuilder getDownloadRequestOrBuilder() {
      if (downloadRequestBuilder_ != null) {
        return downloadRequestBuilder_.getMessageOrBuilder();
      } else {
        return downloadRequest_ == null ?
            entities.DownloadRequest.getDefaultInstance() : downloadRequest_;
      }
    }
    /**
     * <code>.DownloadRequest downloadRequest = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.DownloadRequest, entities.DownloadRequest.Builder, entities.DownloadRequestOrBuilder> 
        getDownloadRequestFieldBuilder() {
      if (downloadRequestBuilder_ == null) {
        downloadRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.DownloadRequest, entities.DownloadRequest.Builder, entities.DownloadRequestOrBuilder>(
                getDownloadRequest(),
                getParentForChildren(),
                isClean());
        downloadRequest_ = null;
      }
      return downloadRequestBuilder_;
    }

    private entities.DownloadResponse downloadResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.DownloadResponse, entities.DownloadResponse.Builder, entities.DownloadResponseOrBuilder> downloadResponseBuilder_;
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public boolean hasDownloadResponse() {
      return downloadResponseBuilder_ != null || downloadResponse_ != null;
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public entities.DownloadResponse getDownloadResponse() {
      if (downloadResponseBuilder_ == null) {
        return downloadResponse_ == null ? entities.DownloadResponse.getDefaultInstance() : downloadResponse_;
      } else {
        return downloadResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public Builder setDownloadResponse(entities.DownloadResponse value) {
      if (downloadResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        downloadResponse_ = value;
        onChanged();
      } else {
        downloadResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public Builder setDownloadResponse(
        entities.DownloadResponse.Builder builderForValue) {
      if (downloadResponseBuilder_ == null) {
        downloadResponse_ = builderForValue.build();
        onChanged();
      } else {
        downloadResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public Builder mergeDownloadResponse(entities.DownloadResponse value) {
      if (downloadResponseBuilder_ == null) {
        if (downloadResponse_ != null) {
          downloadResponse_ =
            entities.DownloadResponse.newBuilder(downloadResponse_).mergeFrom(value).buildPartial();
        } else {
          downloadResponse_ = value;
        }
        onChanged();
      } else {
        downloadResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public Builder clearDownloadResponse() {
      if (downloadResponseBuilder_ == null) {
        downloadResponse_ = null;
        onChanged();
      } else {
        downloadResponse_ = null;
        downloadResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public entities.DownloadResponse.Builder getDownloadResponseBuilder() {
      
      onChanged();
      return getDownloadResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    public entities.DownloadResponseOrBuilder getDownloadResponseOrBuilder() {
      if (downloadResponseBuilder_ != null) {
        return downloadResponseBuilder_.getMessageOrBuilder();
      } else {
        return downloadResponse_ == null ?
            entities.DownloadResponse.getDefaultInstance() : downloadResponse_;
      }
    }
    /**
     * <code>.DownloadResponse downloadResponse = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        entities.DownloadResponse, entities.DownloadResponse.Builder, entities.DownloadResponseOrBuilder> 
        getDownloadResponseFieldBuilder() {
      if (downloadResponseBuilder_ == null) {
        downloadResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            entities.DownloadResponse, entities.DownloadResponse.Builder, entities.DownloadResponseOrBuilder>(
                getDownloadResponse(),
                getParentForChildren(),
                isClean());
        downloadResponse_ = null;
      }
      return downloadResponseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message)
  }

  // @@protoc_insertion_point(class_scope:Message)
  private static final entities.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new entities.Message();
  }

  public static entities.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  public entities.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

