// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface NodeReplicationStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeReplicationStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   */
  entities.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  entities.NodeOrBuilder getNodeOrBuilder();

  /**
   * <code>string chunkIndex = 2;</code>
   */
  java.lang.String getChunkIndex();
  /**
   * <code>string chunkIndex = 2;</code>
   */
  com.google.protobuf.ByteString
      getChunkIndexBytes();

  /**
   * <code>.Status status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 3;</code>
   */
  entities.Status getStatus();
}
