// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface NodeSearchResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NodeSearchResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   */
  entities.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  entities.NodeOrBuilder getNodeOrBuilder();

  /**
   * <code>.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 2;</code>
   */
  entities.Status getStatus();

  /**
   * <code>repeated .FileInfo files = 3;</code>
   */
  java.util.List<entities.FileInfo> 
      getFilesList();
  /**
   * <code>repeated .FileInfo files = 3;</code>
   */
  entities.FileInfo getFiles(int index);
  /**
   * <code>repeated .FileInfo files = 3;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .FileInfo files = 3;</code>
   */
  java.util.List<? extends entities.FileInfoOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .FileInfo files = 3;</code>
   */
  entities.FileInfoOrBuilder getFilesOrBuilder(
      int index);
}
