// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface ReplicateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReplicateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.FileInfo fileInfo = 1;</code>
   */
  boolean hasFileInfo();
  /**
   * <code>.FileInfo fileInfo = 1;</code>
   */
  entities.FileInfo getFileInfo();
  /**
   * <code>.FileInfo fileInfo = 1;</code>
   */
  entities.FileInfoOrBuilder getFileInfoOrBuilder();
}
