// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public final class Torr {
  private Torr() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChunkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeReplicationStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeReplicationStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeSearchResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeSearchResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocalSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalSearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocalSearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReplicateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReplicateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReplicateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReplicateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChunkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChunkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DownloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DownloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DownloadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DownloadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntorr.proto\"\"\n\004Node\022\014\n\004host\030\001 \001(\t\022\014\n\004po" +
      "rt\030\002 \001(\005\"6\n\tChunkInfo\022\r\n\005index\030\001 \001(\r\022\014\n\004" +
      "size\030\002 \001(\r\022\014\n\004hash\030\003 \001(\014\"T\n\010FileInfo\022\014\n\004" +
      "hash\030\001 \001(\014\022\014\n\004size\030\002 \001(\r\022\020\n\010filename\030\003 \001" +
      "(\t\022\032\n\006chunks\030\004 \003(\0132\n.ChunkInfo\"Y\n\025NodeRe" +
      "plicationStatus\022\023\n\004node\030\001 \001(\0132\005.Node\022\022\n\n" +
      "chunkIndex\030\002 \001(\t\022\027\n\006status\030\003 \001(\0162\007.Statu" +
      "s\"Z\n\020NodeSearchResult\022\023\n\004node\030\001 \001(\0132\005.No" +
      "de\022\027\n\006status\030\002 \001(\0162\007.Status\022\030\n\005files\030\003 \003" +
      "(\0132\t.FileInfo\"#\n\022LocalSearchRequest\022\r\n\005r" +
      "egex\030\001 \001(\t\"K\n\023LocalSearchResponse\022\027\n\006sta" +
      "tus\030\001 \001(\0162\007.Status\022\033\n\010fileInfo\030\002 \003(\0132\t.F" +
      "ileInfo\"\036\n\rSearchRequest\022\r\n\005regex\030\001 \001(\t\"" +
      "M\n\016SearchResponse\022\027\n\006status\030\001 \001(\0162\007.Stat" +
      "us\022\"\n\007results\030\002 \003(\0132\021.NodeSearchResult\"/" +
      "\n\rUploadRequest\022\020\n\010filename\030\001 \001(\t\022\014\n\004dat" +
      "a\030\002 \001(\014\"F\n\016UploadResponse\022\027\n\006status\030\001 \001(" +
      "\0162\007.Status\022\033\n\010fileInfo\030\002 \001(\0132\t.FileInfo\"" +
      "/\n\020ReplicateRequest\022\033\n\010fileInfo\030\001 \001(\0132\t." +
      "FileInfo\"\\\n\021ReplicateResponse\022\027\n\006status\030" +
      "\001 \001(\0162\007.Status\022.\n\016nodeStatusList\030\002 \003(\0132\026" +
      ".NodeReplicationStatus\"4\n\014ChunkRequest\022\020" +
      "\n\010fileHash\030\001 \001(\014\022\022\n\nchunkIndex\030\002 \001(\005\"6\n\r" +
      "ChunkResponse\022\027\n\006status\030\001 \001(\0162\007.Status\022\014" +
      "\n\004data\030\002 \001(\014\"#\n\017DownloadRequest\022\020\n\010fileH" +
      "ash\030\001 \001(\014\"9\n\020DownloadResponse\022\027\n\006status\030" +
      "\001 \001(\0162\007.Status\022\014\n\004data\030\002 \001(\014\"\275\006\n\007Message" +
      "\022\033\n\004type\030\001 \001(\0162\r.Message.Type\022/\n\022localSe" +
      "archRequest\030\002 \001(\0132\023.LocalSearchRequest\0221" +
      "\n\023localSearchResponse\030\003 \001(\0132\024.LocalSearc" +
      "hResponse\022%\n\rsearchRequest\030\004 \001(\0132\016.Searc" +
      "hRequest\022\'\n\016searchResponse\030\005 \001(\0132\017.Searc" +
      "hResponse\022%\n\ruploadRequest\030\006 \001(\0132\016.Uploa" +
      "dRequest\022\'\n\016uploadResponse\030\007 \001(\0132\017.Uploa" +
      "dResponse\022+\n\020replicateRequest\030\010 \001(\0132\021.Re" +
      "plicateRequest\022-\n\021replicateResponse\030\t \001(" +
      "\0132\022.ReplicateResponse\022#\n\014chunkRequest\030\n " +
      "\001(\0132\r.ChunkRequest\022%\n\rchunkResponse\030\013 \001(" +
      "\0132\016.ChunkResponse\022)\n\017downloadRequest\030\014 \001" +
      "(\0132\020.DownloadRequest\022+\n\020downloadResponse" +
      "\030\r \001(\0132\021.DownloadResponse\"\220\002\n\004Type\022\030\n\024LO" +
      "CAL_SEARCH_REQUEST\020\000\022\031\n\025LOCAL_SEARCH_RES" +
      "PONSE\020\001\022\022\n\016SEARCH_REQUEST\020\002\022\023\n\017SEARCH_RE" +
      "SPONSE\020\003\022\022\n\016UPLOAD_REQUEST\020\004\022\023\n\017UPLOAD_R" +
      "ESPONSE\020\005\022\025\n\021REPLICATE_REQUEST\020\006\022\026\n\022REPL" +
      "ICATE_RESPONSE\020\007\022\021\n\rCHUNK_REQUEST\020\010\022\022\n\016C" +
      "HUNK_RESPONSE\020\t\022\024\n\020DOWNLOAD_REQUEST\020\n\022\025\n" +
      "\021DOWNLOAD_RESPONSE\020\013*\330\001\n\006Status\022\013\n\007SUCCE" +
      "SS\020\000\022\033\n\027ERROR_MALFORMED_MESSAGE\020\001\022\030\n\024ERR" +
      "OR_CORRUPTED_DATA\020\002\022\031\n\025ERROR_GENERAL_FAI" +
      "LURE\020\003\022&\n\"ERROR_FILE_ALREADY_PRESENT_LOC" +
      "ALLY\020\004\022\026\n\022ERROR_STORAGE_FULL\020\005\022\026\n\022ERROR_" +
      "NO_SUCH_FILE\020\006\022\027\n\023ERROR_NO_SUCH_CHUNK\020\007B" +
      "\014\n\010entitiesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Node_descriptor,
        new java.lang.String[] { "Host", "Port", });
    internal_static_ChunkInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChunkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChunkInfo_descriptor,
        new java.lang.String[] { "Index", "Size", "Hash", });
    internal_static_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileInfo_descriptor,
        new java.lang.String[] { "Hash", "Size", "Filename", "Chunks", });
    internal_static_NodeReplicationStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NodeReplicationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeReplicationStatus_descriptor,
        new java.lang.String[] { "Node", "ChunkIndex", "Status", });
    internal_static_NodeSearchResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_NodeSearchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeSearchResult_descriptor,
        new java.lang.String[] { "Node", "Status", "Files", });
    internal_static_LocalSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LocalSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocalSearchRequest_descriptor,
        new java.lang.String[] { "Regex", });
    internal_static_LocalSearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_LocalSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocalSearchResponse_descriptor,
        new java.lang.String[] { "Status", "FileInfo", });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Regex", });
    internal_static_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResponse_descriptor,
        new java.lang.String[] { "Status", "Results", });
    internal_static_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadRequest_descriptor,
        new java.lang.String[] { "Filename", "Data", });
    internal_static_UploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_UploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadResponse_descriptor,
        new java.lang.String[] { "Status", "FileInfo", });
    internal_static_ReplicateRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ReplicateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReplicateRequest_descriptor,
        new java.lang.String[] { "FileInfo", });
    internal_static_ReplicateResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ReplicateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReplicateResponse_descriptor,
        new java.lang.String[] { "Status", "NodeStatusList", });
    internal_static_ChunkRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ChunkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChunkRequest_descriptor,
        new java.lang.String[] { "FileHash", "ChunkIndex", });
    internal_static_ChunkResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ChunkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChunkResponse_descriptor,
        new java.lang.String[] { "Status", "Data", });
    internal_static_DownloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_DownloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DownloadRequest_descriptor,
        new java.lang.String[] { "FileHash", });
    internal_static_DownloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_DownloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DownloadResponse_descriptor,
        new java.lang.String[] { "Status", "Data", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Type", "LocalSearchRequest", "LocalSearchResponse", "SearchRequest", "SearchResponse", "UploadRequest", "UploadResponse", "ReplicateRequest", "ReplicateResponse", "ChunkRequest", "ChunkResponse", "DownloadRequest", "DownloadResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
