// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: torr.proto

package entities;

public interface UploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.Status status = 1;</code>
   */
  entities.Status getStatus();

  /**
   * <code>.FileInfo fileInfo = 2;</code>
   */
  boolean hasFileInfo();
  /**
   * <code>.FileInfo fileInfo = 2;</code>
   */
  entities.FileInfo getFileInfo();
  /**
   * <code>.FileInfo fileInfo = 2;</code>
   */
  entities.FileInfoOrBuilder getFileInfoOrBuilder();
}
